using System.Collections.Generic;

namespace ParbadGateway.PasargadRest.Internal
{
    internal class PasargadErrorHandler
    {
        private static readonly List<ErrorInfo> ErrorList = new List<ErrorInfo>
        {
            new ErrorInfo { Code = 0, EnglishMessage = "success", PersianMessage = "تراکنش موفق است" },
            new ErrorInfo { Code = 1, EnglishMessage = "failure", PersianMessage = "ناموفق" },
            new ErrorInfo { Code = 2, EnglishMessage = "Unknown", PersianMessage = "نامشخص" },
            new ErrorInfo { Code = 401, EnglishMessage = "not authorized", PersianMessage = "مجاز به استفاده از سرویس نیستید" },
            new ErrorInfo { Code = 500, EnglishMessage = "Internal server error", PersianMessage = "خطا داخلی سرور" },
            new ErrorInfo { Code = 13000, EnglishMessage = "Input Invalid", PersianMessage = "ورودی نامعتبر است" },
            new ErrorInfo { Code = 13001, EnglishMessage = "url Invalid", PersianMessage = "آدرس نامعتبر است" },
            new ErrorInfo { Code = 13002, EnglishMessage = "token url Invalid", PersianMessage = "توکن نامعتبر است" },
            new ErrorInfo { Code = 13003, EnglishMessage = "unique not is Invoice", PersianMessage = "کد رهگیری یکتا نیست" },
            new ErrorInfo { Code = 13004, EnglishMessage = "empty is Token", PersianMessage = "توکن خالی است" },
            new ErrorInfo { Code = 13005, EnglishMessage = "out time Gateway", PersianMessage = "عدم امکان دسترسی موقت به سرور" },
            new ErrorInfo { Code = 13007, EnglishMessage = "expired is captcha", PersianMessage = "کپچا منقضی شده است" },
            new ErrorInfo { Code = 13008, EnglishMessage = "wrong is captcha", PersianMessage = "کپچا اشتباه است" },
            new ErrorInfo { Code = 13009, EnglishMessage = "url token not found", PersianMessage = "توکن یافت نشد" },
            new ErrorInfo { Code = 13010, EnglishMessage = "Number Mobile Invalid", PersianMessage = "شماره موبایل نامعتبر است" },
            new ErrorInfo { Code = 13011, EnglishMessage = "code product Invalid", PersianMessage = "کد محصول نامعتبر است" },
            new ErrorInfo { Code = 13012, EnglishMessage = "id bill Invalid", PersianMessage = "شناسه قبض نامعتبر است" },
            new ErrorInfo { Code = 13013, EnglishMessage = "id payment Invalid", PersianMessage = "شناسه پرداخت نامعتبر است" },
            new ErrorInfo { Code = 13015, EnglishMessage = "between each api call must be 2 minutes", PersianMessage = "برای فراخوانی مجدد 2 دقیقه صبر کنید" },
            new ErrorInfo { Code = 13016, EnglishMessage = "found not Transaction", PersianMessage = "تراکنش یافت نشد" },
            new ErrorInfo { Code = 13017, EnglishMessage = "Length Input Invalid", PersianMessage = "طول ورودی نامعتبر است" },
            new ErrorInfo { Code = 13018, EnglishMessage = "Found Not", PersianMessage = "یافت نشد" },
            new ErrorInfo { Code = 13019, EnglishMessage = "Invoice is not match with login user", PersianMessage = "کد رهگیری برای کاربر لاگین شده وجود ندارد" },
            new ErrorInfo { Code = 13020, EnglishMessage = "Exception has Code Company Check", PersianMessage = "خطا هنگام چک کردن کد شرکت" },
            new ErrorInfo { Code = 13021, EnglishMessage = "cancelled been has already Page Payment", PersianMessage = "پرداخت از پیش لغو شده است" },
            new ErrorInfo { Code = 13022, EnglishMessage = "payed not transaction", PersianMessage = "تراکنش پرداخت نشده است" },
            new ErrorInfo { Code = 13025, EnglishMessage = "success not transaction", PersianMessage = "تراکنش ناموفق است" },
            new ErrorInfo { Code = 13026, EnglishMessage = "CardNumber Invalid", PersianMessage = "شماره کارت نامعتبر است" },
            new ErrorInfo { Code = 13027, EnglishMessage = "Mobile number and CardNumber are not match", PersianMessage = "شماره موبایل برای شماره کارت وارد شده نیست" },
            new ErrorInfo { Code = 13028, EnglishMessage = "callback domain is not valid", PersianMessage = "آدرس کالبک نامعتبر است" },
            new ErrorInfo { Code = 13029, EnglishMessage = "transaction before is verified and it's success", PersianMessage = "تراکنش موفق و تایید شده است" },
            new ErrorInfo { Code = 13030, EnglishMessage = "transaction before is verified and it's failed", PersianMessage = "تراکنش تایید شده و ناموفق است" },
            new ErrorInfo { Code = 13031, EnglishMessage = "transaction is not yet verified", PersianMessage = "تراکنش منتظر تایید است" },
            new ErrorInfo { Code = 13032, EnglishMessage = "card Expired", PersianMessage = "کارت منقضی شده است" },
            new ErrorInfo { Code = 13033, EnglishMessage = "transaction before is reversed and it’s successful", PersianMessage = "تراکنش بازگشت با موفقیت انجام شده است" },
            new ErrorInfo { Code = 13035, EnglishMessage = "Transaction are not allowed for reverse", PersianMessage = "تراکنش مجاز به انجام عملیات بازگشت نمی باشد" },
            new ErrorInfo { Code = 13045, EnglishMessage = "transaction canceled holder Card", PersianMessage = "دارنده کارت تراکنش را لغو کرد" },
            new ErrorInfo { Code = 13046, EnglishMessage = "setteled Already", PersianMessage = "تراکنش تسویه شده است" },
            new ErrorInfo { Code = 13047, EnglishMessage = "merchant Invalid", PersianMessage = "پذیرنده کارت نامعتبر است" },
            new ErrorInfo { Code = 13049, EnglishMessage = "transaction Incomplete", PersianMessage = "تراکنش کامل نشده است" },
            new ErrorInfo { Code = 13054, EnglishMessage = "transaction Invalid", PersianMessage = "تراکنش نامعتبر است" },
            new ErrorInfo { Code = 13055, EnglishMessage = "amount transaction Invalid", PersianMessage = "مبلغ تراکنش نامعتبر است" },
            new ErrorInfo { Code = 13056, EnglishMessage = "issuer card Invalid", PersianMessage = "صادرکننده کارت نامعتبر است" },
            new ErrorInfo { Code = 13057, EnglishMessage = "date card Expired", PersianMessage = "تاریخ کارت منقضی شده است" },
            new ErrorInfo { Code = 13058, EnglishMessage = "blocked temporarily is Card", PersianMessage = "کارت موقتاً مسدود شده است" },
            new ErrorInfo { Code = 13059, EnglishMessage = "account Undefined", PersianMessage = "حساب تعریف نشده است" },
            new ErrorInfo { Code = 13060, EnglishMessage = "type transaction Invalid", PersianMessage = "نوع تراکنش نامعتبر است" },
            new ErrorInfo { Code = 13061, EnglishMessage = "identifier transfer Invalid", PersianMessage = "شناسه انتقال نامعتبر است" },
            new ErrorInfo { Code = 13062, EnglishMessage = "Duplicate transfer identifier", PersianMessage = "تراکنش تکراری" },
            new ErrorInfo { Code = 13063, EnglishMessage = "Amount is not enough", PersianMessage = "مبلغ کافی نیست" },
            new ErrorInfo { Code = 13064, EnglishMessage = "pin Incorrect", PersianMessage = "پین اشتباه است" },
            new ErrorInfo { Code = 13065, EnglishMessage = "No card record", PersianMessage = "کارت نامعتبر است" },
            new ErrorInfo { Code = 13066, EnglishMessage = "Service not allowed on card", PersianMessage = "سرویس روی کارت مجاز نیست" },
            new ErrorInfo { Code = 13067, EnglishMessage = "Card not allowed on terminal", PersianMessage = "کارت برای ترمینال مجاز نیست" },
            new ErrorInfo { Code = 13068, EnglishMessage = "Transaction amount over limit", PersianMessage = "مبلغ تراکنش بیش از حد مجاز است" },
            new ErrorInfo { Code = 13069, EnglishMessage = "Card Restricted", PersianMessage = "کارت محدود است" },
            new ErrorInfo { Code = 13070, EnglishMessage = "Security error", PersianMessage = "خطای امنیتی" },
            new ErrorInfo { Code = 13071, EnglishMessage = "Transaction amount is not match with finalprice" , PersianMessage = "مبلغ تراکنش با قیمت نهایی مطابقت ندارد" },
            new ErrorInfo { Code = 13072, EnglishMessage = "Limit than more is request Transaction" , PersianMessage = "درخواست تراکنش بیش از حد مجاز است"},
            new ErrorInfo { Code = 13073, EnglishMessage = "Account Inactive" , PersianMessage = "حساب غیر فعال است"},
            new ErrorInfo { Code = 13074, EnglishMessage = "Terminal by cardBlock" , PersianMessage = "کارت توسط ترمینال مسدود شد"},
            new ErrorInfo { Code = 13075, EnglishMessage = "Expired time Confirm" , PersianMessage = "زمان تأییدیه منقضی شده است"},
            new ErrorInfo { Code = 13076, EnglishMessage = "Expire time Reverse" , PersianMessage = "زمان اصالحیه منقضی شده است"},
            new ErrorInfo { Code = 13077, EnglishMessage = "Transaction original Invalid" , PersianMessage = "تراکنش اصلی نامعتبر است"},
            new ErrorInfo { Code = 13078, EnglishMessage = "Amount interchange Incorrect" , PersianMessage = "مبلغ اشتباه است"},
            new ErrorInfo { Code = 13079, EnglishMessage = "Day working Invalid" , PersianMessage = "روز کاری نامعتبراست"},
            new ErrorInfo { Code = 13080, EnglishMessage = "Card Inactive" , PersianMessage = "کارت غیر فعال است"},
            new ErrorInfo { Code = 13081, EnglishMessage = "Account card Invalid" , PersianMessage = "حساب کارت نامعتبر است"},
            new ErrorInfo { Code = 13082, EnglishMessage = "Transaction successful Not" , PersianMessage = "تراکنش ناموفق است"},
            new ErrorInfo { Code = 13083, EnglishMessage = "Data encrypted Invalid" , PersianMessage = "داده های رمزگذاری شده نامعتبر است"},
            new ErrorInfo { Code = 13084, EnglishMessage = "Off signed Shaparak or Switch" , PersianMessage = "سوئیچ یا شاپرک خاموش است"},
            new ErrorInfo { Code = 13085, EnglishMessage = "Bank destination down Host" , PersianMessage = "میزبان بانک مقصد پایین است"},
            new ErrorInfo { Code = 13086, EnglishMessage = "Data confirm Invalid" , PersianMessage = "اطلاعات تاییدیه نامعتبر است"},
            new ErrorInfo { Code = 13087, EnglishMessage = "Switch or shaparak signing off" , PersianMessage = "سوئیچ یا شاپرک در حال خاموش شدن است"},
            new ErrorInfo { Code = 13088, EnglishMessage = "Key encrypted Invalid" , PersianMessage = "کلید رمزگذاری شده نامعتبر است"},
            new ErrorInfo { Code = 13089, EnglishMessage = "Banned transaction with contact interface" , PersianMessage = "انجام تراکنش با واسط غیرتماسی مردود شده است، تراکنش با واسط تماسی انجام گردد"},
            new ErrorInfo { Code = 13090, EnglishMessage = "Day work End" , PersianMessage = "پایان روز کاری"},
            new ErrorInfo { Code = 13091, EnglishMessage = "Inactive is Switch" , PersianMessage = "سوئیچ غیر فعال است"},
            new ErrorInfo { Code = 13092, EnglishMessage = "There is no way to send transaction" , PersianMessage = "نامعتبر کارت صادرکننده"},
            new ErrorInfo { Code = 13093, EnglishMessage = "Transaction does not done success" , PersianMessage = "آمیز موفقیت تراکنش نیست"},
            new ErrorInfo { Code = 13094, EnglishMessage = "Transaction Duplicate" , PersianMessage = "تراکنش تکراری است"},
            new ErrorInfo { Code = 13095, EnglishMessage = "Pin old Incorrect" , PersianMessage = "پین قدیمی اشتباه است"},
            new ErrorInfo { Code = 13096, EnglishMessage = "Error Systematic" , PersianMessage = "خطای داخلی سوئیچ"},
            new ErrorInfo { Code = 13097, EnglishMessage = "Exchanging Key" , PersianMessage = "در حال انجام فرآیند تغییر کلید"},
            new ErrorInfo { Code = 13098, EnglishMessage = "Limit over pin Static" , PersianMessage = "پین استاتیک فراتر از محدودیت"},
            new ErrorInfo { Code = 13099, EnglishMessage = "Terminal Invalid" , PersianMessage = "پایانه فروش نامعتبر است"},
            new ErrorInfo { Code = 13300, EnglishMessage = "Inactive Terminal" , PersianMessage = "پایانه در سیستم غیرفعال است"},
            new ErrorInfo { Code = 13301, EnglishMessage = "Merchant Invalid" , PersianMessage = "فروشگاه در سیستم تعریف نشده است"},
            new ErrorInfo { Code = 13302, EnglishMessage = "Format code national Invalid" , PersianMessage = "فرمت کد ملی نامعتبر است"},
            new ErrorInfo { Code = 13303, EnglishMessage = "Password terminal Invalid" , PersianMessage = "پسورد ترمینال نامعتبر است"},
            new ErrorInfo { Code = 13304, EnglishMessage = "PaymentID bill Invalid" , PersianMessage = "شناسه پرداخت نامعتبر است"},
            new ErrorInfo { Code = 13305, EnglishMessage = "Data transaction Insufficient" , PersianMessage = "داده های تراکنش ناکافی است"},
            new ErrorInfo { Code = 13306, EnglishMessage = "Code evoucher Invalid" , PersianMessage = "کد شارژ نامعتبر است"},
            new ErrorInfo { Code = 13307, EnglishMessage = "Card or pin timeout" , PersianMessage = "مهلت زمانی برای کارت یا پین به پایان رسیده است"},
            new ErrorInfo { Code = 13308, EnglishMessage = "Info account Unrecognized" , PersianMessage = "اطلاعات حساب ناشناس است"},
            new ErrorInfo { Code = 13309, EnglishMessage = "Important Not" , PersianMessage = "مهم نیست"},
            new ErrorInfo { Code = 13310, EnglishMessage = "Error Other" , PersianMessage = "خطای دیگر"},
            new ErrorInfo { Code = 13311, EnglishMessage = "Sold charge All" , PersianMessage = "تمام شارژها فروخته شده"},
            new ErrorInfo { Code = 13312, EnglishMessage = "Available not Charge" , PersianMessage = "شارژ موجود نیست"},
            new ErrorInfo { Code = 13313, EnglishMessage = "Available not is Operator" , PersianMessage = "اپراتور در دسترس نیست"},
            new ErrorInfo { Code = 13314, EnglishMessage = "Null is number Mobile" , PersianMessage = "شماره موبایل خالی است"},
            new ErrorInfo { Code = 13315, EnglishMessage = "Error reverse Topup" , PersianMessage = "در رزرو فاکتور مشکلی وجود دارد"},
            new ErrorInfo { Code = 13316, EnglishMessage = "Settlement transaction must be confirm or reverse" , PersianMessage = "اصل تراکنش مالی موفق نمیباشد"},
            new ErrorInfo { Code = 13317, EnglishMessage = "Wrong is Captcha" , PersianMessage = "کپچا اشتباه است"},
            new ErrorInfo { Code = 13318, EnglishMessage = "Code company Invalid" , PersianMessage = "کد سازمان ناموجود"},
            new ErrorInfo { Code = 13319, EnglishMessage = "EOF" , PersianMessage = "سیستم با اختلال همراه است"},
            new ErrorInfo { Code = 13320, EnglishMessage = "Fraud suspected Card" , PersianMessage = "کارت مشکوک به کلاهبرداری"},
            new ErrorInfo { Code = 13321, EnglishMessage = "Found not additional Terminal" , PersianMessage = "اطلاعات تکمیلی پایانه موجود نیست"},
            new ErrorInfo { Code = 13322, EnglishMessage = "Retry max reached OTP" , PersianMessage = "درخواست رمز پویا بیش از حد مجاز"},
            new ErrorInfo { Code = 13323, EnglishMessage = "Failed inquiry card Broker" , PersianMessage = "عدم انطباق کد ملی با شماره کارت"},
            new ErrorInfo { Code = 13324, EnglishMessage = "Success not was transaction Original" , PersianMessage = "اصل تراکنش مالی موفق نمیباشد"},
            new ErrorInfo { Code = 13325, EnglishMessage = "Original transaction was not Found" , PersianMessage = "تراکنش اصل یافت نشد"},
            new ErrorInfo { Code = 13326, EnglishMessage = "Card blocked by machine" , PersianMessage = "کارت مسدود شده است"},
            new ErrorInfo { Code = 13327, EnglishMessage = "Card blocked by machine for special condition" , PersianMessage = "کارت به دلایل ویژه مسدود شده است"},
            new ErrorInfo { Code = 13328, EnglishMessage = "Holder card authentication with Success" , PersianMessage = "احراز هویت دارنده کارت با موفقیت انجام شد"},
            new ErrorInfo { Code = 13329, EnglishMessage = "Doing will Confirm" , PersianMessage = "سیستم مشغول است"},
            new ErrorInfo { Code = 13330, EnglishMessage = "Wage Invalid" , PersianMessage = "کارمزد نامعتبر است"},
            new ErrorInfo { Code = 13331, EnglishMessage = "PSP is not supported By shaparak" , PersianMessage = "شاپرک توسط PSP پشتیبانی نمی‌شود"},
            new ErrorInfo { Code = 13332, EnglishMessage = "Card suspected fraud card block by terminal" , PersianMessage = "کارت مشکوک به کلاهبرداری است"},
            new ErrorInfo { Code = 13333, EnglishMessage = "Limit over is pin entry Wrong" , PersianMessage = "ورود پین از حد مجاز گذشته است"},
            new ErrorInfo { Code = 13334, EnglishMessage = "Card lost Response" , PersianMessage = "کارت گمشده است"},
            new ErrorInfo { Code = 13335, EnglishMessage = "Card stolen" , PersianMessage = "کارت سرقت شده است"},
            new ErrorInfo { Code = 13336, EnglishMessage = "No public account" , PersianMessage = "کارت حساب عمومی ندارد"},
            new ErrorInfo { Code = 13337, EnglishMessage = "Card has no current account",PersianMessage= "حساب تعریف نشده است"},
            new ErrorInfo { Code = 13338, EnglishMessage = "Late too is Response",PersianMessage= "پاسخ خیلی دیر دریافت شد"},
            new ErrorInfo { Code = 13339, EnglishMessage = "CardHolder Account Status Is Bad",PersianMessage= "کارت یا حساب مبدا در وضعیت نامناسب می‌باشد"},
            new ErrorInfo { Code = 13340, EnglishMessage = "Terminal Account Status Is Bad",PersianMessage= "کارت یا حساب مقصد در وضعیت نامناسب می‌باشد"},
            new ErrorInfo { Code = 13341, EnglishMessage = "Limit Than More Is Entry Pin Wrong",PersianMessage= "ورود پین اشتباه بیش از حد مجاز است"},
            new ErrorInfo { Code = 13342, EnglishMessage = "Merchant is not valid",PersianMessage= "فروشگاه نامعتبر است"},
            new ErrorInfo { Code = 13343, EnglishMessage = "Error register Card",PersianMessage= "خطای داخلی ثبت کارت"},
            new ErrorInfo { Code = 13344, EnglishMessage = "Pan Duplicate",PersianMessage= "شماره کارت تکراری است"},
            new ErrorInfo { Code = 13345, EnglishMessage = "Number phone Invalid",PersianMessage= "فرمت شماره موبایل نامعتبر است"},
            new ErrorInfo { Code = 13346, EnglishMessage = "Code national Invalid",PersianMessage= "فرمت شماره شناسنامه نامعتبر است"},
            new ErrorInfo { Code = 13347, EnglishMessage = "Code company or code national Invalid",PersianMessage= "کد ملی یا سازمان تکراری است"},
            new ErrorInfo { Code = 13348, EnglishMessage = "Validate request Error",PersianMessage= "خطای اعتبارسنجی"},
            new ErrorInfo { Code = 13350, EnglishMessage = "Format Invoice is not valid",PersianMessage= "قالب شماره فاکتور معتبر نیست"},
            new ErrorInfo { Code = 13351, EnglishMessage = "Username is not valid",PersianMessage= "نام کاربری معتبر نیست"},
            new ErrorInfo { Code = 13352, EnglishMessage = "Operator access has been revoked",PersianMessage= "دسترسی اپراتور لغو شده است"},
            new ErrorInfo { Code = 13353, EnglishMessage = "Service access has been revoked",PersianMessage= "دسترسی سرویس لغو شده است"},
            new ErrorInfo { Code = 13354, EnglishMessage = "Operator credit is not sufficient",PersianMessage= "اعتبار اپراتور کافی نیست"},
            new ErrorInfo { Code = 13355, EnglishMessage = "There is a problem in invoice reservation",PersianMessage= "در رزرو فاکتور مشکلی وجود دارد"},
            new ErrorInfo { Code = 13356, EnglishMessage = "Service credit is not sufficient",PersianMessage= "اعتبار سرویس کافی نیست"},
            new ErrorInfo { Code = 13357, EnglishMessage = "Transaction status must be unknown",PersianMessage= "وضعیت تراکنش باید نامشخص باشد"},
            new ErrorInfo { Code = 13358, EnglishMessage = "Protocol type does not detected",PersianMessage= "پروتکل یافت نشد"},
            new ErrorInfo { Code = 13359, EnglishMessage = "Original transaction must be financial",PersianMessage= "تراکنش اصلی باید مالی باشد"},
            new ErrorInfo { Code = 13360, EnglishMessage = "Transaction Settlement failed",PersianMessage= "تراکنش تسویه ناموفق است"},
            new ErrorInfo { Code = 13361, EnglishMessage = "Type of bill is incorrect",PersianMessage= "نوع وصول آنی نامعتبر می‌باشد"},
            new ErrorInfo { Code = 13365, EnglishMessage = "Transaction Not implemented",PersianMessage= "تراکنش پشتیبانی نمی‌شود"},
            new ErrorInfo { Code = 13366, EnglishMessage = "Err token is not active",PersianMessage= "توکن فعال نشده است"},
            new ErrorInfo { Code = 13367, EnglishMessage = "Err unexpected signing method",PersianMessage= "فرمت ورود نامعتبر است"},
            new ErrorInfo { Code = 13368, EnglishMessage = "Err oauth login",PersianMessage= "خطای ورود"},
            new ErrorInfo { Code = 13369, EnglishMessage = "Err Invalid Input",PersianMessage= "فرمت ورودی نامعتبر است"},
            new ErrorInfo { Code = 13370, EnglishMessage = "Err time frame exceeding limit",PersianMessage= "خطای محدودیت در زمان"},
            new ErrorInfo { Code = 13371, EnglishMessage = "Reporter permission error",PersianMessage= "خطای دسترسی گزارش‌گر"},
            new ErrorInfo { Code = 13372, EnglishMessage = "Dns error",PersianMessage= "خطای بازیابی آدرس"},
            new ErrorInfo { Code = 13373, EnglishMessage = "Terminal group doesnt exist",PersianMessage= "گروه ترمینال یافت نشد"},
            new ErrorInfo { Code = 13374, EnglishMessage = "Request error",PersianMessage= "خطای درخواست"},
            new ErrorInfo { Code = 13375, EnglishMessage = "Invalid phone number",PersianMessage= "شماره تلفن نامعتبر است"},
            new ErrorInfo { Code = 13376, EnglishMessage = "Evaluation Error",PersianMessage= "خطای اعتبارسنجی"},
            new ErrorInfo { Code = 13377, EnglishMessage = "Atomic operation Error",PersianMessage= "خطا در تراکنش"},
            new ErrorInfo { Code = 13378, EnglishMessage = "Protocol Error",PersianMessage= "خطای پروتکل"},
            new ErrorInfo { Code = 13379, EnglishMessage = "Invalid pinBlock",PersianMessage= "پین بالک نامعتبر است"},
            new ErrorInfo { Code = 13380, EnglishMessage = "Cvv2 is not valid",PersianMessage= "CVV2 نامعتبر است"},
            new ErrorInfo { Code = 13381, EnglishMessage = "Cellphone number format incorrect",PersianMessage= "فرمت شماره تماس نادرست است"},
            new ErrorInfo { Code = 13382, EnglishMessage = "Invalid reverse MTI",PersianMessage= "خطا در نوع اصلاحیه"},
            new ErrorInfo { Code = 13383, EnglishMessage = "Settlement action not found",PersianMessage= "تراکنش تسویه شده است"},
            new ErrorInfo { Code = 13384, EnglishMessage = "Invalid encryptPin",PersianMessage= "رمز اشتباه است"},
            new ErrorInfo { Code = 13385, EnglishMessage = "Response duplicated record",PersianMessage= "رکورد تکراری است"},
            new ErrorInfo { Code = 13386, EnglishMessage = "Publish error",PersianMessage= "خطا در انتقال"},
            new ErrorInfo { Code = 13390, EnglishMessage = "Image resize Error",PersianMessage= "خطا در تغییر سایز تصویر"},
            new ErrorInfo { Code = 13391, EnglishMessage = "Invalid sql parameter",PersianMessage= "خطا در پارامترهای ورودی"},
            new ErrorInfo { Code = 13392, EnglishMessage = "Hsm request error",PersianMessage= "خطا در درخواست رمزنگاری سخت‌افزاری"},
            new ErrorInfo { Code = 13393, EnglishMessage = "Request not found",PersianMessage= "درخواستی یافت نشد"},
            new ErrorInfo { Code = 13394, EnglishMessage = "Unmarshal Error",PersianMessage= "خطا در فرمت ورودی"},
            new ErrorInfo { Code = 13395, EnglishMessage = "Refund Rejected",PersianMessage= "تراکنش برگشت از خرید ناموفق است"},
            new ErrorInfo { Code = 13396, EnglishMessage = "Invalid terminal serial number",PersianMessage= "خطا در سریال پایانه فروش"},
            new ErrorInfo { Code = 13397, EnglishMessage = "Transaction ReEnter",PersianMessage= "ورود مجدد تراکنش"},
            new ErrorInfo { Code = 13398, EnglishMessage = "Captcha Retry Max Reached",PersianMessage= "درخواست کپچا بیش از حد مجاز است"},
            new ErrorInfo { Code = 13399, EnglishMessage = "Invalid Terminal Number",PersianMessage= "ترمینال یافت نشد"},
            new ErrorInfo { Code = 13400, EnglishMessage = "Public Key Not Found",PersianMessage= "کلید عمومی یافت نشد"},
            new ErrorInfo { Code = 13401, EnglishMessage = "Voucher Not Available",PersianMessage= "شارژ مورد نظر موجود نیست"},
            new ErrorInfo { Code = 13402, EnglishMessage = "Invalid Referer",PersianMessage= "ارجاع دهنده با اطلاعات ثبت شده تطابق ندارد"},
            new ErrorInfo { Code = 13403, EnglishMessage = "Invalid IBAN Merchant",PersianMessage= "شبا معتبر نیست"},
            new ErrorInfo { Code = 13404, EnglishMessage = "Conversion Type Failed",PersianMessage= "خطا در تغییر نوع متغیر"},
            new ErrorInfo { Code = 13405, EnglishMessage = "Empty Value",PersianMessage= "مقدار خالی"},
            new ErrorInfo { Code = 13406, EnglishMessage = "Operation Failed",PersianMessage= "عملیات به خطا خورد"},
            new ErrorInfo { Code = 13407, EnglishMessage = "Invalid Authentication",PersianMessage= "خطا در احراز هویت"},
            new ErrorInfo { Code = 13408, EnglishMessage = "Invalid Organization Code",PersianMessage= "کد سازمان یافت نشد"},
            new ErrorInfo { Code = 13409, EnglishMessage = "Invalid Offset",PersianMessage= "خطا در Offset"},
            new ErrorInfo { Code = 13410, EnglishMessage = "Invalid Page Size",PersianMessage= "خطا در سایز صفحه"},
            new ErrorInfo { Code = 13411, EnglishMessage = "Hash Failed",PersianMessage= "خطا در هم‌سازی"},
            new ErrorInfo { Code = 13412, EnglishMessage = "ParseField Failed",PersianMessage= "خطا در خواندن مقدار"},
            new ErrorInfo { Code = 13413, EnglishMessage = "Invalid Action",PersianMessage= "خطا در عملیات"},
            new ErrorInfo { Code = 13414, EnglishMessage = "No Rows Were Updated",PersianMessage= "خطا در آپدیت"},
            new ErrorInfo { Code = 13415, EnglishMessage = "Invalid Purchase Identifier",PersianMessage= "خطا در خرید شناسه‌دار"},
            new ErrorInfo { Code = 13416, EnglishMessage = "Invalid Multi Payment Data",PersianMessage= "خطای چندشبایی"},
            new ErrorInfo { Code = 13417, EnglishMessage = "Not Implemented",PersianMessage= "عملیات مورد نظر پیاده‌سازی نشده است"},
            new ErrorInfo { Code = 13418, EnglishMessage = "Invalid Transaction Request Time",PersianMessage= "خطا در تاریخ درخواست"},
            new ErrorInfo { Code = 13419, EnglishMessage = "Invalid Logon Transaction Time",PersianMessage= "خطا در زمان ورود"},

        };
        public static string GetErrorMessage(int code, bool returnPersian = false)
        {
            var error = ErrorList.Find(e => e.Code == code);
            if (error != null)
            {
                return returnPersian ? error.PersianMessage : error.EnglishMessage;
            }
            return returnPersian ? "کد خطا یافت نشد" : "Error code not found";
        }
    }

}
